sudo: false
language: python
python:
  - '3.6'

branches:
  only:
  - blog

install:
- pip install -r requirements.txt

script:
- make publish travis_ci

env:
  global:
    secure: "ZadW1+KoFYE3vmqHn1fyTNZEZs8m2SlqI+p9xolZD7kJ1eVAU5jGDfC8r9avQJJoFDZ63H0RpKm9kI6Ha5buJBePLOxq1uP8bFPbFGCLwywe407E1APTZoGylMulTKYTbSpEy4DzMgouR8ci78Cei1xarjvqwrBTPNeOvwzZD0bz0aVVSZKRGj1wRk/wFlOC8PateGIvF+cxflsLFkvW8rD8LRWxkpFDtZhXKQG4DEAQmVbqdxrxEiiH7ndHWPgyNm6XAXaFteK4/ysgX3lkBxy6vq0ZCgMPwLLsf1VUTGZBN7EGTe21zUuBVp9tFmRtCAoRgZI0FsI5j49+pnLW0FwTSmws654nDxH0Kpay4nnjdt8LfO3H7MmTn7gNnBeHOqn+CqWJwWercyzDlbhOG9RLzrBNykeEzLXMVFdiyjZW+Q/tAc2AYt2cpZLUk+vOOgMtTbh0T1HtxWffXRBdGseGvr23aY4r+UK9EDr5AO7/tZOwN3EqJtfA75cPuljhYXpRG4EhW7GzjuqWLPqk3HE8HRCfSK33GbTI5liR4C0MLeDqKO9uShaftUXQPG7cygWgUiU9pWhaLTvQWtawLLU5IUuWrb8cCRK9il1/fT67JKwis3yvG8wjG/ze9BMz74WAbv+QSs2gbLlzSMnfar4ewuFmcNRka2p++VwVCfo="
