sudo: false
language: python
python:
  - '3.6'

branches:
  only:
  - blog

install:
- pip install -r requirements.txt

script:
- make publish travis_ci

env:
  global:
    secure: "DO69SbE2MudJPjIZQq09XTCLqdvvv/KCmj7rwiza19kLjBXrWu8luo4DCYoyp951YcWlKScZ9ZHv6e/7t+PPnZsIBC4iCBzUQhZAwfADO0X8y6hClWP+WInEjDTAnIV3he5dAN6+InpZOiaEF3dhUf9OlbxLRV9CczCrm53tbqeaho8AXPMx/+ksInZgjWGDu3fy7WCRL58aGZFCwta5uAV9MMYDYHmSliNT5zEBoTqEA1+uw7aqTWpW3V75z8CoE8HzBF2W4DUVhldIqDMCjcK5aNKeFExPSwyRX+tDU7zL2iMTVoQ8F2bqll3XpYWxZyJ82InknVkVcpYyBrExSgO2SbgPz9OnZh2HmkmJunMTLDyQ14BwpfXM8e91u6CNdSZEU9qxbl7PIi/7HgXy9soCz7PQkrpzFTqQByfqtdTbmebNLFV0x6/4bU7in+fjbCF/jAFB7JFqIFcJlDoSd0YHBUCQzU1lHR/RuY9BBvpxbMyUcwBmEKah2kfDNqUP/oixerjBKpuwVvra5wNjuIfNKeZaTdFyxSniP3j/XpmCdPLKqcOtxxCZSg2hwUb5Tk3/HMJzuA4WaoDA/XiP7Q6NVQRGWIy6C6C3F9EAq6stwX9o2Q3s6FEBzhe664ckCgQTt9TmkEZluMpTufWv45Gs/OqcLICDeOJqWy9RhNA="
