sudo: false
language: python
python:
  - '3.6'

branches:
  only:
  - blog

install:
- pip install -r requirements.txt

script:
- echo OUATH $GH_OA_TOKEN
- make publish travis_ci

env:
  global:
    secure: "k6Ry/KL4B/HV5HPCZ6FqlL5L7YNtY0ZCw3Z7bmjIKxd5/5tiEcJZMmprLv0bgtMwOABJ963o4Cx3JealmWjXEu6GbVwzWs4sRBgfXWJJeI3MBOqazKd2AEX275QBmYQkXWzOOf5i2SSznmKcFAWkiThl8zdx5tioJdK/Q4yPvWc3VI2TqQhtY8Pf6j63IjjFfM/uzGFGnM0cgomLdCB7lvG7xuhrqYVHHWmbWjel9TVbf+AS5Z1/b/IOqjxaOGP4GwtkswVUPTxjVMtkVG9dBJeR2KcM/MPpBEmcxviPje0Ef38xMZsmPjkJ9AG0pMzkaMuRQe+lCWLiC7HkRBaCc71bJAYsbvLhSSYA587QctsRT3DOeVqbGPoz5heVmkuBqRyjTUkymGeu5hTDzMOrDdjpe4Eyhz6hZuX+WNqoq/oYx9FAuyasDUT0OwHmQiOAFuV7uqA+A8wi+AW8ZcrwImsCDGSkprPdyrO/oecyyaPMl4bVfhC4LO7zm4oSZbfM22/mFAIZamETomyl1KrNDVM9f+NSMA/lU7MWkfU1zlNAMbAEMH7MRk+JBTC2BtywjEK+xt/l/Ddv4X/PwY4aA5o+XT4fNUPD1XdwH9BH6fTUz4B0zIMle2pSM6W8oa028YUoNHo/fDp83URTBE6B7NlJ6DwBmu8rMYe0oSh/Kds="
